@extends('template')
@section('content')
    <table>
        <thead>
            <td>
                Name
            </td>
            <td>
                Price
            </td>
        </thead>
        <tbody>
            <tr>
                <td>
                    abcd
                </td>
                <td>
                    def
                </td>
            </tr>
            <tr>
                <td>
                    abcd
                </td>
                <td>
                    def
                </td>
            </tr>
        </tbody>
    </table>
    
@endsection